project:
  type: website
  output-dir: docs

website:
  title: "類家 千怜"
  site-url: https://ruike316.github.io/portfolio/
  repo-url: https://github.com/ruike316/portfolio
  favicon: images/favicon.svg
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: ホーム
      - href: profile.qmd
        text: 自己紹介
      - href: papers.qmd
        text: 論文
      - href: presentations.qmd
        text: 発表
      - href: awards.qmd
        text: 受賞
      - href: contact.qmd
        text: 連絡先
    right:
      - text: 言語
        menu:
          - href: index.qmd
            text: 日本語
          - href: en/index.qmd
            text: English
      - icon: github
        href: https://github.com/ruike316
      # - icon: instagram
      #   href: https://www.instagram.com/___toilet/

format:
  html:
    theme:
      - cosmo
      - custom.scss
    css: styles.css
    toc: true
    page-layout: full
    fontsize: 1.1em
    linestretch: 1.5
    grid:
      sidebar-width: 300px
      body-width: 900px
      margin-width: 300px
    include-in-header:
      text: |
        <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;500;600;700&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">



